# Generated by Django 3.0.6 on 2021-12-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='gender',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffs',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='staffs/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='students/%Y/%m/%d/'),
        ),
    ]
