# Generated by Django 3.0.6 on 2021-12-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_auto_20211208_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='profile_pic',
            field=models.FileField(blank=True, upload_to='staffs/'),
        ),
    ]
